version: 2.1

orbs:
  sq: escaletech/sonarqube@0.2
  gh-release: escaletech/gh-conventional-release@0.1.9

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
            - go-mod-v2-
      - run:
          name: Check if go.mod is clean
          command: go mod tidy && git diff --quiet
      - run: make test-coverage
      - persist_to_workspace:
          root: .
          paths: [coverage]
  sonar:
    docker:
      - image: cimg/go:1.16
    steps:
      - attach_workspace:
          at: .
      - sq/scanner

production_only: &production_only
  filters:
    branches: { ignore: /.*/ }
    tags: { only: /^v.*/ }

ci_only: &ci_only
  filters:
    branches: { ignore: [main] }
    tags: { ignore: /.*/ }

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test:
          <<: *ci_only
      - sonar:
          context: sonarqube
          requires: [build-and-test]
          <<: *ci_only
  production:
    jobs:
      - build-and-test:
          <<: *production_only
      - gh-release/create-release:
          context: github-create-release
          requires: [build-and-test]
          <<: *production_only
